---
title: "Chocolate Muffins or Cupcakes"
author: "Claire To"
date: "2024-09-13"
categories: [recipes]
title-block-banner: true
---

Chocolate muffins and cupcakes are basically the same, aren't they? Except cupcakes have added frosting? This has been my most repeated recipes since it's so easy and satisfies my chocolate cravings! With 1/4 cup honey, the bitterness is comparable to 90% dark chocolate to me, so I recommend you double the sugar if you prefer sweeter. This recipe makes 12 cupcakes.

## Ingredients

### Dry Ingredients

-   1 cup all-purpose flour

-   1/2 cup cocoa or cacao powder (cacao is the healthier option)

-   1 tsp baking powder

-   1/2 tsp baking soda

-   1/2 tsp salt

### Wet Ingredients

-   1/2 cup milk

-   1/4-1/2 cup honey or maple syrup

-   1/4 cup olive oil

-   1 large egg

-   1/2 tsp vanilla

### Water

-   1/2 cup boiling bold expresso water

## Instructions

1.  Preheat oven to 325ยบ F.
2.  Add dry ingredients in a large bowl and whisk to combine well.
3.  Add wet ingredients (excluding expresso) in another bowl and mix to combine well.
4.  Combine the dry and wet ingredients and mix well on medium speed.
5.  Reduce speed and add in boiling water.
6.  Beat on high speed for about 1 minute to add air into the batter.
7.  Fill cupcake liner about 1/2 full.
8.  Bake until a toothpick inserted in the center comes out clean about 20 min.

## Frosting

Combine the following and pipe or spread onto cupcakes.

-   1 large ripe avocado

-   1 tbsp coconut oil

-   1/3 cup cocoa or cacao powder

-   2-4 tbsp honey or maple syrup

-   1 tbsp milk
