---
title: "Sea Salt Vanilla Custard Ice Cream"
author: "Claire To"
date: "2024-09-23"
categories: [recipes]
title-block-banner: true
---

Most ice creams, especially vanilla, are flavored with "natural flavors" which are not natural at all! It is nearly the same as artificial flavors, the only regulation being that it must be derived from any natural source. However, they may contain more than 100 different chemicals, including preservatives, solvents and other substances and still be called "natural flavors". Not to mention all the added preservatives, gums, emulsifiers, and colorings in ice creams to increase the visual appeal, texture, and shelf life. I use vanilla extract in this recipe because vanilla beans are so expensive :( but if you have the means to use vanilla, I think it would work elegantly. You can also do a different flavoring or add in, ice cream is fun and flexible! Personally, my favorite combination is topping it off with olive oil and more salt. With these ingredients, I would even argue that ice cream can be a health food since full fat dairy products contain so many vitamins and minerals; honey is anti-inflammatory, antioxidant, and antibacterial; and eggs are arguably the most nutrient dense food ;)

## Ingredients

-   1 1/2 cups heavy cream

-   1 1/2 cups whole milk

-   1/4-1/2 tsp salt

-   4 large egg yolks

-   1/4-1/2 cup honey

-   1 1/2 tsp vanilla extract

## Instructions

1.  Heat the cream, milk, and salt on medium heat, stirring occasionally, until barely starting to simmer.
2.  Whisk the egg yolks together in a bowl.
3.  Temper the egg yolks by slowly adding a little bit of the hot cream mixture, whisking it in to prevent clumps.
4.  Add in the egg yolk mixture to the pot, whisking the mixture together as you pour.
5.  Cook over medium-low heat, stirring frequently, until slightly thickened.
6.  Remove from the stove and whisk in honey and vanilla extract.
7.  Cover and chill for at least 6 hours or overnight before churning in an ice cream maker.
