project:
  type: website
  output-dir: docs

website:
  title: "Claire To"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

