---
title: "Research"
title-block-banner: true
---

#### [Entropy-Bounded Computational Geometry Made Easier and Sensitive to Sortedness](https://arxiv.org/abs/2508.20489)
David Eppstein, Michael T. Goodrich, Abraham M. Illickan, Claire A. To  
[The 37th Canadian Conference on Computational Geometry (CCCG 2025)](https://sites.google.com/view/cccgwads-2025/cccg-2025)  
We study instance optimality--algorithms that achieve the performance of the best correct algorithm on every input, with respect to a measure. By leveraging input structure and sortedness, we design simple algorithms for classic computational geometry problems, including maxima set, convex hull, and visibility, and prove new bounds under a complexity measure sensitive to both properties.  
[Paper](/research/entropy-cccg25-paper.pdf) | 
[Poster](/research/entropy-urop2025-poster.pdf) | 
[Slides](/research/entropy-cccg25-slides.pdf) ([Unabridged](/research/entropy-cccg25-slides-full.pdf))

---

#### [Investigating the Capabilities of Generative AI in Solving Data Structures, Algorithms, and Computability Problems](https://dl.acm.org/doi/10.1145/3641554.3701946)  
Nero Li, Shahar Broner, Yubin Kim, Katrina Mizuo, Elijah Sauder, Claire To, Albert Wang, Ofek Gila, Michael Shindler  
[The 56th Technical Symposium on Computer Science Education (SIGCSE TS 2025)](https://sigcse2025.sigcse.org)  
Our study evaluates the ability of generative AI models to solve advanced problems in data structures, algorithms, and computability. By testing 165 free-response questions across 16 theoretical computer science topics, we analyze the strengths and limitations of these models, highlighting their potential for education and automated tutoring.  
[Paper](/research/theorygpt-sigcse25-paper.pdf) | 
[Slides](/research/theorygpt-sigcse25-slides.pdf)  

---

#### [Common Strategy Patterns of Persuasion in a Mission Critical and Time Sensitive Task](https://www.semdial.org/anthology/papers/Z/Z23/Z23-4019/)
Claire To, Setareh Nasihati Gilani, David Traum  
[The 27th Workshop on the Semantics and Pragmatics of Dialogue (SemDial 2023 - MariLogue)](https://mezzanine.um.si/en/conference/semdial-2023-marilogue/)  
Our research examines persuasion strategies in high-stakes, time-sensitive disaster relief interactions, analyzing how dialogue structure, speech acts, and urgency impact outcomes. By identifying patterns in communication, we explore how situational factors influence decision-making and persuasion effectiveness in crisis scenarios.  
[Paper](/research/hsi-semdial23-paper.pdf) | 
[Poster](/research/hsi-semdial23-poster.pdf) | 
[Slides](/research/hsi-semdial23-slides.pdf)  
